module Everything where

import Prelude
import IndexedContainer
import IndexedContainer.Properties
import IndexedContainer.MonoidalCategory
import IndexedSetContainer
import IndexedMonad
import IndexedMonadMorphism
import IndexedMonad.Examples.Product
import IndexedMonad.Examples.Writer
import IndexedMonad.Examples.IndexedState
import IndexedMonad.Examples.ScopedLambda
